### ISSUE TITLE
Linux containers not cleaned up after VM reboot

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/containerlab#1055]
Suspected cause: https://github.com/srl-labs/containerlab/blob/2d6d77baf9b7c9b15cfdc93c19f74bbf37679a20/runtime/docker/docker.go#L411

When the host system reboots, most containers are removed but a set of Linux containers remains running in isolation

**Comment by hellt** [comment]
As you can see, the reason is in the comment section. Some management
containers (like telemetry stack) may fail over time and the automatic
restart beings them back without human intervention.

Rebooting a node with a lab running is considered to be an incident, and a
manual clean up is expected. Luckily it is a single line bash script

**Comment by jbemmel** [comment]
I would still like to be able to disable this through configuration. When building automated topologies with several simple linux host containers, I prefer them to be cleaned up like the other non-linux containers, and not stick around

Suggestion:
 auto-restart: False (default True)

**Comment by hellt** [comment]
thanks
