### ISSUE TITLE
Cannot partially start or destroy a topology if one of the nodes is not running

### ISSUE THREAD

**Issue by perimore** [srl-labs/containerlab#1444]
It's very frustrating that if say a node fails to start, any subsequent deploy of the topology will complain that other containers are already running:

```
INFO[0000] Containerlab v0.42.0 started                 
INFO[0000] Parsing & checking topology file: topology.yaml 
Error: containers [<list of containers>] already exist. Add '--reconfigure' flag to the deploy command to first remove the containers and then deploy the lab
```

The instruction is to use reconfigure. But this fails as the containers already exist:

```
INFO[0000] Removing <dir> directory... 
Error: containers [<list of containers>] already exist. Add '--reconfigure' flag to the deploy command to first remove the containers and then deploy the lab
```

Then simply trying to destroy the remaining nodes gives an error as some of the nodes in the topology are not running:

```
$ sudo containerlab destroy -a
INFO[0000] Parsing & checking topology file: topology.yaml 
ERRO[0000] Error occurred during the demo lab deletion: could not get container for node <failed node>: Node: <failed node>. containers not found 
Error: error(s) occurred during the deletion. Check log messages
```

The only way around this seems to be then to destroy each node one by one which is a PITA if there are lots of nodes.

**Comment by hellt** [comment]
Unfortunately, we failed to reproduce this issue. It seems it appears only in specific scenarios with Docker API misbehaving and not returning all stopped containers.
Because it never appears in our setups (which we have many) it is impossible for us to troubleshoot this without users' being able to interrogate their setup.

To remove all containers which belong to a certain lab in one go you can do the following:

```bash
docker ps --filter "name=clab-srl" -q | xargs -n1 docker rm --force
```

This command removes every container whose name starts with `clab-srl`, which means any container that belongs to a lab named `srl`

/cc @steiler

**Comment by steiler** [comment]
Found the issue.
further details in #1413

**Comment by perimore** [comment]
Yes, I was sure this worked in an earlier version
