### ISSUE TITLE
Do not use WARN log message for missing SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#1555]
When no SSH_AUTH_SOCK env var present we do not extract keys from the agent, but a missing env var shouldn't be logged as WARN. It is a subtle internal mechanics that don't qualify to propagate to the main log. Should be DEBUG

**Comment by steiler** [comment]
But
- failed opening SSH_AUTH_SOCK
- error listing agent's pub keys
 and 
 - error parsing the keys 
 are still considered warnings? Or do you expect changes there as well?
 I tend to think it would still be warnings, because the pre-condition of having an SSH_AUTH_SOCK defined is there so it should work extracting and listing the keys... opinion?

**Comment by steiler** [comment]
see #1559

**Comment by steiler** [comment]
fixed
