### ISSUE TITLE
IXR6 , no routes on Show BGP 

### ISSUE THREAD

**Issue by mohamadrahhal** [srl-labs/containerlab#1687]
![image](https://github.com/srl-labs/containerlab/assets/149397480/265959b3-e4ce-4a1b-a9a4-ccb578b22240)

**Comment by hellt** [comment]
Hi @mohamadrahhal 
this is not a containerlab issue, for SR Linux related questions you can ask stuff in our Discord - https://discord.gg/tZvgjQ6PZf

The reason you have this issue is probably because you run IXR6 with an older SW version (`show version` to check). The afi-safi container was introduced in 23.3 if I remember correclty

**Comment by mohamadrahhal** [comment]
hello , hellt thank you for your reply: this is what i get when i put show version , moreover i have asked on discord also.

![image](https://github.com/srl-labs/containerlab/assets/149397480/31375d71-7aff-43d6-b126-9c54766a5051)
