### ISSUE TITLE
Make default MTU settings more realistic

### ISSUE THREAD

**Issue by networkop** [srl-labs/containerlab#392]
The current MTU default is 65000 which is not realistic in physical networking context.  Could we change this to e.g. 9000?

**Comment by jbemmel** [comment]
Or 9001 like aws

**Comment by hellt** [comment]
as we synced with @networkop offline and briefly discussed this I am inclined to close it with the following reasoning:

containerlab doesn't need to impose any limitation by default on the underlying network carried out via veth pairs. We took 65k as this is ~max MTU for the veth link in linux kernel.

The idea here is that the NOS that starts will impose its max MTU on the links that it senses are available. To not be in the way of the NOS defaults we jack up the MTU.
So far this was never a problem and it is not also an issue with the platform @networkop is working with.

So how about we park it for now since no-one has issues with 65k MTU so far except for it being non-natural and see if this causes any issues in the long run.
