### ISSUE TITLE
Config template input values

### ISSUE THREAD

**Issue by networkop** [srl-labs/containerlab#393]
I've been reading about the [config](https://containerlab.srlinux.dev/manual/nodes/#config) (Go template) that can be passed in as one of the inputs.
Is it possible to document what kind of format it expects and how to customize the target path for it?

**Comment by hellt** [comment]
The user-facing config generation will be part of #383.

I need to change that documentation piece, since the template variables that users can pass to the existing `config` element under a node is something that is set by the kind implementation.
As of tooday there is no way to provide user-defined variables that will be passed to a config template referenced in the `config`. The `config` is used solely to pass entire configs at this moment

**Comment by networkop** [comment]
yep, that's cool. I'm fine with static templates, just want to understand the structure of the input.

**Comment by hellt** [comment]
Sure, no worries! That helps us understand where docs have some gaps 
Closing this as it seems to be answered
