### ISSUE TITLE
crpd races to read the config while interfaces are still connecting

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#560]
as reported in https://github.com/srl-labs/containerlab/issues/552#issuecomment-887715629 we need to check if interfaces that are being created after the crpd node starts prevent crpd from reading the startup config which references those interfaces

**Comment by hellt** [comment]
if this happens to be the race, then a potential fix would be to be able to create the nodes but not start them
and only start them after all the links are attached

**Comment by topranks** [comment]
Thanks @hellt.  I will do more tests tomorrow.

Specifically I’ll remove the vlan interface stuff I added and see if I can reproduce without that.  i.e. can it happen with only references in the provided JunOS config to interfaces containerlab itself has created.

If not then it may just be my own issue due to how I was approaching it, which I can probably work around.

**Comment by topranks** [comment]
Hi @hellt 

Thanks for you time on this.  I've re-tested today and I cannot reproduce the issue, if my configuration only references devices that containerlab itself creates (i.e. I stripped out all the vlan interfaces I was creating after deploy / referencing in the JunOS config).

So I do not think there is an issue here that will affect normal users who are using clab as designed.  You can close this ticket.

**Comment by hellt** [comment]
got it, thanks @topranks
feel free to reopen if that will surface in the future
