### ISSUE TITLE
add podman support

### ISSUE THREAD

**Issue by LimeHat** [srl-labs/containerlab#643]
I'm going to give it a shot since you already got an interface, posting this just for the tracking purposes.

**Comment by LimeHat** [comment]
Hi Grigory,
yep, I am; work in progress. I can share an alpha branch sometime next week

**Comment by hellt** [comment]
the podman (beta) support has been added
Soon I will carve out 0.23.0 release with these changes

**Comment by cgb** [comment]
Podman 4.0 was released recently too with some major networking changes, not sure how this will affect the integration work but just a heads up :)

https://github.com/containers/podman/releases/tag/v4.0.0

**Comment by LimeHat** [comment]
Thanks @cgb. We're planning to work on adding v4 support in March.

**Comment by q2dg** [comment]
I'm running Containerlab v0.42.0 in a Fedora 38 system with Podman 4.5.1
When I run _sudo containerlab deploy -t linux.clab.yml -r podman_ I get this error:

Error: unable to connect to Podman socket: Get "http://d/v4.5.1/libpod/_ping": dial unix /run//podman/podman.sock: connect: no such file or directory

What's going on? I need Containerlab to run over Podman because nowadays Docker isn't available in RedHat based host systems

P.S: On the other hand, if Podman can run rootless containers, could it be possibe to run containerlab in rootless mode too? This would be a game changer. Thanks!

**Comment by q2dg** [comment]
Sorry, I needed to start Podman service first: sudo systemctl start podman
However, I get another error message:

failed to run postdeploy task for node cont1: failed to Statfs "/run/netns/netns-421753a3-065e-aef4-b860-1b5d71b21570": no such file or directory
