### ISSUE TITLE
stop lab from being deployed if srlinux nodes are used and cpu <2

### ISSUE THREAD

**Issue by hellt** [srl-labs/containerlab#769]
srl nodes won't run with a single vcpu

**Comment by JakeBednard** [comment]
I think I hit this today, with no error output or stopping from CLAB. I had `cpu-set` to a single CPU, and SRLinux nodes were not able to bring their interfaces up, instead marking "Down, No Transceiver" (or something like that). I'll retest in the future, but what is the expected/intended CLAB behavior when a single CPU is assigned, so that I can confirm?

**Comment by hellt** [comment]
Hi
In this case the fix was to stop srl deployment if a single vcpu was found on the host. When you set the cpu-set to a single core we dont have a check for that. So currently you will have to allocate more than 1 vcpu for srl nodes to make them work
